// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_IpDc1iZ-NTEyGXdbGnufTdFt8mPbRLI',
    appId: '1:448529679160:web:34c1ef03361938275277cd',
    messagingSenderId: '448529679160',
    projectId: 'rigel-fl-app',
    authDomain: 'rigel-fl-app.firebaseapp.com',
    databaseURL: 'https://rigel-fl-app-default-rtdb.firebaseio.com',
    storageBucket: 'rigel-fl-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQMexM1LxYxbLcbh1KZddItDmy87PbA78',
    appId: '1:448529679160:android:eace28e2e93979b95277cd',
    messagingSenderId: '448529679160',
    projectId: 'rigel-fl-app',
    databaseURL: 'https://rigel-fl-app-default-rtdb.firebaseio.com',
    storageBucket: 'rigel-fl-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJaLMig_3xHr3dqSDomoJsI6Sm89xr1XI',
    appId: '1:448529679160:ios:9cf472460acf23795277cd',
    messagingSenderId: '448529679160',
    projectId: 'rigel-fl-app',
    databaseURL: 'https://rigel-fl-app-default-rtdb.firebaseio.com',
    storageBucket: 'rigel-fl-app.appspot.com',
    iosClientId: '448529679160-1acr68lvhueaftrfaur1orin75cpq1h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rigelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJaLMig_3xHr3dqSDomoJsI6Sm89xr1XI',
    appId: '1:448529679160:ios:9cf472460acf23795277cd',
    messagingSenderId: '448529679160',
    projectId: 'rigel-fl-app',
    databaseURL: 'https://rigel-fl-app-default-rtdb.firebaseio.com',
    storageBucket: 'rigel-fl-app.appspot.com',
    iosClientId: '448529679160-1acr68lvhueaftrfaur1orin75cpq1h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rigelApp',
  );
}
